# Generated by Django 6.0 on 2026-01-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_outlet", "0002_alter_book_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
